### ISSUE TITLE
Commit a composer.lock to the VCS?

### ISSUE THREAD

**Issue by bocharsky-bw** [knpuniversity/Gladiator#1]
Should we to commit `composer.lock` to the VCS? It's absent in repo now.

**Comment by weaverryan** [comment]
It should be absent as this is a library, not a project. For example, `symfony/symfony` also doesn't have a lock file - but `symfony/symfony-standard` does. So, no lock file here I think!

**Comment by bocharsky-bw** [comment]
Hm, I don't think about it. Thanks :+1:
